"""initial schema

Revision ID: 2070c00e77d0
Revises: 
Create Date: 2026-08-04 11:11:05.307137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '2070c00e77d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('assigned_to_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('reminder_before_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('google_calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_calendar_synced', sa.Boolean(), nullable=False),
    sa.Column('google_calendar_synced_at', sa.DateTime(), nullable=True),
    sa.Column('meet_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_assigned_to_id'), 'calendar', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_calendar_created_by_id'), 'calendar', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_calendar_end_date'), 'calendar', ['end_date'], unique=False)
    op.create_index(op.f('ix_calendar_event_type'), 'calendar', ['event_type'], unique=False)
    op.create_index(op.f('ix_calendar_owner_id'), 'calendar', ['owner_id'], unique=False)
    op.create_index(op.f('ix_calendar_start_date'), 'calendar', ['start_date'], unique=False)
    op.create_index(op.f('ix_calendar_tenant_id'), 'calendar', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_calendar_title'), 'calendar', ['title'], unique=False)
    op.create_table('user_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('request_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('reviewed_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_requests_request_type'), 'user_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_user_requests_tenant_id'), 'user_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_requests_user_id'), 'user_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_requests_user_id'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_tenant_id'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_request_type'), table_name='user_requests')
    op.drop_table('user_requests')
    op.drop_index(op.f('ix_calendar_title'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_tenant_id'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_start_date'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_owner_id'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_event_type'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_end_date'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_created_by_id'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_assigned_to_id'), table_name='calendar')
    op.drop_table('calendar')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
