"""aria tables

Revision ID: 1103be68c7ad
Revises: 364c5a7ae92f
Create Date: 2026-08-04 08:35:54.881846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '1103be68c7ad'
down_revision = '364c5a7ae92f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aria_subscription_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_is_active', sa.Boolean(), nullable=True),
    sa.Column('next_payment', sa.DateTime(), nullable=True),
    sa.Column('last_event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aria_subscription_states_tenant_id'), 'aria_subscription_states', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_aria_subscription_states_user_email'), 'aria_subscription_states', ['user_email'], unique=False)
    op.create_index(op.f('ix_aria_subscription_states_user_id'), 'aria_subscription_states', ['user_id'], unique=False)
    op.create_table('aria_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aria_webhook_events_event_key'), 'aria_webhook_events', ['event_key'], unique=True)
    op.create_index(op.f('ix_aria_webhook_events_event_type'), 'aria_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_aria_webhook_events_tenant_id'), 'aria_webhook_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_aria_webhook_events_user_email'), 'aria_webhook_events', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aria_webhook_events_user_email'), table_name='aria_webhook_events')
    op.drop_index(op.f('ix_aria_webhook_events_tenant_id'), table_name='aria_webhook_events')
    op.drop_index(op.f('ix_aria_webhook_events_event_type'), table_name='aria_webhook_events')
    op.drop_index(op.f('ix_aria_webhook_events_event_key'), table_name='aria_webhook_events')
    op.drop_table('aria_webhook_events')
    op.drop_index(op.f('ix_aria_subscription_states_user_id'), table_name='aria_subscription_states')
    op.drop_index(op.f('ix_aria_subscription_states_user_email'), table_name='aria_subscription_states')
    op.drop_index(op.f('ix_aria_subscription_states_tenant_id'), table_name='aria_subscription_states')
    op.drop_table('aria_subscription_states')
    # ### end Alembic commands ###
