"""initial schema

Revision ID: 0ad3db0f014d
Revises: 
Create Date: 2026-08-03 23:59:12.115497

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '0ad3db0f014d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain_status', sa.Enum('PENDING', 'VERIFYING', 'ACTIVE', 'FAILED', name='domainstatus'), nullable=False),
    sa.Column('cloudflare_zone_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloudflare_custom_hostname_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloudflare_dns_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenantstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('billing_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_custom_domain'), 'tenants', ['custom_domain'], unique=True)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('tenant_domains',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFYING', 'ACTIVE', 'FAILED', name='domainstatus'), nullable=False),
    sa.Column('cloudflare_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloudflare_hostname_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ssl_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_domains_domain'), 'tenant_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_tenant_domains_tenant_id'), 'tenant_domains', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_domains_tenant_id'), table_name='tenant_domains')
    op.drop_index(op.f('ix_tenant_domains_domain'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_custom_domain'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
